powerCosumptionData <- read.delim("../exdata%2Fdata%2Fhousehold_power_consumption/household_power_consumption.txt",
                                  sep=";")
powerCosumptionData$Date <- as.Date(powerCosumptionData$Date,format = "%d/%m/%Y")
data1 <- subset(powerCosumptionData, Date >= as.Date("01/02/2007",format = "%d/%m/%Y"))
datafinal <- subset(data1, Date <= as.Date("02/02/2007",format = "%d/%m/%Y"))
datafinal$Global_active_power <- as.numeric(datafinal$Global_active_power)
datafinal$datetime <- strptime(paste(datafinal$Date,datafinal$Time),format = "%Y-%m-%d %H:%M:%S")
with(data = datafinal, plot(x=datetime,y=Global_active_power,type="l",xlab="",ylab="Global Active Power"))
dev.copy(png,"plot2.png",width=480,height=480)
dev.off()